import { useState, useEffect, useRef, useCallback } from "react";
import { SPRITE_SRC } from "./spriteData.js";
const TW=96,TH=48,MW=31,MH=31,WS=0.045,RH=60,ND=1,FP=4,SPW=24,SPH=32,DW=56,DH=74;

const FACING_MAP={
  se:{stand:[1,0],walk:[[2,0],[3,0]]},
  ne:{stand:[1,1],walk:[[2,0],[3,0]]},
  sw:{stand:[0,1],walk:[[2,1],[3,1]]},
  nw:{stand:[0,0],walk:[[2,1],[3,1]]},
};

function genMaze(w,h){const m=Array.from({length:h},()=>Array(w).fill(1));const d=[[0,-2],[0,2],[-2,0],[2,0]];function sh(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}function c(x,y){m[y][x]=0;for(const[dx,dy]of sh([...d])){const nx=x+dx,ny=y+dy;if(nx>0&&nx<w-1&&ny>0&&ny<h-1&&m[ny][nx]===1){m[y+dy/2][x+dx/2]=0;c(nx,ny);}}}c(1,1);for(let i=0;i<w*h*0.12;i++){const rx=1+Math.floor(Math.random()*(w-2)),ry=1+Math.floor(Math.random()*(h-2));if(m[ry][rx]===1){let a=0;if(ry>0&&m[ry-1][rx]===0)a++;if(ry<h-1&&m[ry+1][rx]===0)a++;if(rx>0&&m[ry][rx-1]===0)a++;if(rx<w-1&&m[ry][rx+1]===0)a++;if(a>=2)m[ry][rx]=0;}}return m;}
function placeFloor(maze,n,av){const it=[],s=new Set(av.map(p=>`${p.x},${p.y}`));let a=0;while(it.length<n&&a<3000){const x=1+Math.floor(Math.random()*(MW-2)),y=1+Math.floor(Math.random()*(MH-2));if(maze[y][x]===0&&!s.has(`${x},${y}`)){it.push({x,y});s.add(`${x},${y}`);}a++;}return it;}
function placeWall(maze,n,av){const it=[],s=new Set(av.map(p=>`${p.x},${p.y}`));let a=0;while(it.length<n&&a<3000){const x=1+Math.floor(Math.random()*(MW-2)),y=1+Math.floor(Math.random()*(MH-2));if(maze[y][x]===1){let adj=false;[[0,-1],[0,1],[-1,0],[1,0]].forEach(([dx,dy])=>{const nx=x+dx,ny=y+dy;if(nx>=0&&nx<MW&&ny>=0&&ny<MH&&maze[ny][nx]===0)adj=true;});if(adj&&!s.has(`${x},${y}`)){it.push({x,y});s.add(`${x},${y}`);}}a++;}return it;}
function toIso(gx,gy){return{x:(gx-gy)*TW/2,y:(gx+gy)*TH/2};}
function tR(x,y,s){let h=x*374761393+y*668265263+s*1274126177;h=(h^(h>>13))*1103515245;return((h^(h>>16))&0x7fffffff)/0x7fffffff;}
function useIsMobile(){const[m,s]=useState(false);useEffect(()=>{const c=()=>s(('ontouchstart' in window||navigator.maxTouchPoints>0)&&window.innerWidth<768);c();window.addEventListener('resize',c);return()=>window.removeEventListener('resize',c);},[]);return m;}
function DPadBtn({icon,onPress,size}){const iRef=useRef(null),pRef=useRef(false);const go=(e)=>{e.preventDefault();if(pRef.current)return;pRef.current=true;onPress();iRef.current=setInterval(onPress,180);};const stop=(e)=>{if(e)e.preventDefault();pRef.current=false;if(iRef.current){clearInterval(iRef.current);iRef.current=null;}};useEffect(()=>()=>{if(iRef.current)clearInterval(iRef.current);},[]);return <button onTouchStart={go} onTouchEnd={stop} onTouchCancel={stop} onMouseDown={go} onMouseUp={stop} onMouseLeave={stop} style={{width:size,height:size,borderRadius:8,background:'rgba(0,170,255,0.08)',border:'1.5px solid rgba(0,170,255,0.25)',color:'rgba(0,220,255,0.8)',fontSize:18,fontFamily:'monospace',display:'flex',alignItems:'center',justifyContent:'center',touchAction:'manipulation',userSelect:'none',WebkitUserSelect:'none',cursor:'pointer',padding:0}}>{icon}</button>;}
function CrossDPad({onMove,size}){const s=size||46,g=3;return <div style={{display:'grid',gridTemplateColumns:`${s}px ${s}px ${s}px`,gridTemplateRows:`${s}px ${s}px ${s}px`,gap:g,flexShrink:0}}><div/><DPadBtn icon="▲" size={s} onPress={()=>onMove(0,-1)}/><div/><DPadBtn icon="◀" size={s} onPress={()=>onMove(-1,0)}/><div style={{width:s,height:s}}/><DPadBtn icon="▶" size={s} onPress={()=>onMove(1,0)}/><div/><DPadBtn icon="▼" size={s} onPress={()=>onMove(0,1)}/><div/></div>;}

export default function DataCenterMaze(){const canvasRef=useRef(null);const[gs,setGs]=useState(null);const[dims,setDims]=useState({w:1400,h:850});const keysRef=useRef(new Set()),lastMoveRef=useRef(0),particlesRef=useRef([]),gRef=useRef(null);const walkRef=useRef({x:1,y:1,moving:false,walkCycle:0}),camRef=useRef({x:0,y:0});const revealedRef=useRef(new Uint8Array(MW*MH));const notifRef=useRef({text:'',timer:0});const sparksRef=useRef([]);const spriteRef=useRef(null);const[showPhone,setShowPhone]=useState(false);const isMobile=useIsMobile();useEffect(()=>{const img=new Image();img.onload=()=>{spriteRef.current=img;};img.src=SPRITE_SRC;},[]);useEffect(()=>{const r=()=>{const vw=window.innerWidth,vh=window.innerHeight;if(vw<768)setDims({w:Math.min(vw*2,1200),h:Math.floor(vh*0.65*2)});else setDims({w:Math.min(1400,Math.floor(vw*0.96)),h:Math.min(850,Math.floor(vh*0.88))});};r();window.addEventListener('resize',r);return()=>window.removeEventListener('resize',r);},[]);
